# .buildkite/pipeline.yml
# Simple pipeline that works with default Buildkite setup

steps:
  - label: "🔧 Setup & Lint"
    command: |
      echo "--- Setting up environment"
      java -version || echo "Java not found, will use Docker"
      
      echo "--- Making gradlew executable"
      chmod +x gradlew
      
      echo "--- Running Lint"
      ./gradlew lint || echo "Lint failed, but continuing"
      
      echo "--- Uploading lint results"
      buildkite-agent artifact upload "app/build/reports/lint-results-*.html" || true
    # No agent queue specified - uses default

  - wait

  - label: "🚀 Android Build with Docker"
    plugins:
        - docker#v5.0.0:
            image: "cimg/android:2024.01"
            environment:
              - "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64"
    command: |
        echo "+++ Java Version"
        java -version
        
        echo "+++ Build Debug APK"
        chmod +x gradlew
        ./gradlew assembleDebug
        
        echo "+++ Build Release APK"
        ./gradlew assembleRelease
      artifact_paths:
        - "app/build/outputs/apk/**/*.apk"

  - wait

  - label: "📊 Build Summary"
    command: |
      echo "Build #${BUILDKITE_BUILD_NUMBER} completed!"
      echo "Branch: ${BUILDKITE_BRANCH}"
      echo "Commit: ${BUILDKITE_COMMIT:0:7}"
      buildkite-agent artifact list || true

