# .buildkite/pipeline.yml
# Simple pipeline that works with default Buildkite setup

steps:
  - label: "🔧 Setup & Lint"
    command: |
      echo "--- Setting up environment"
      java -version || echo "Java not found, will use Docker"
      
      echo "--- Making gradlew executable"
      chmod +x gradlew
      
      echo "--- Running Lint"
      ./gradlew lint || echo "Lint failed, but continuing"
      
      echo "--- Uploading lint results"
      buildkite-agent artifact upload "app/build/reports/lint-results-*.html" || true
    # No agent queue specified - uses default

  - wait

  - label: "📱 Build APKs"
    command: |
      echo "--- Building Debug APK"
      chmod +x gradlew
      ./gradlew assembleDebug
      
      echo "--- Building Release APK"
      ./gradlew assembleRelease
      
      echo "--- Uploading APKs"
      buildkite-agent artifact upload "app/build/outputs/apk/**/*.apk"

  - wait

  - label: "📊 Build Summary"
    command: |
      echo "Build #${BUILDKITE_BUILD_NUMBER} completed!"
      echo "Branch: ${BUILDKITE_BRANCH}"
      echo "Commit: ${BUILDKITE_COMMIT:0:7}"
      buildkite-agent artifact list || true

